from flask import Blueprint, jsonify, request, current_app
from backend.db_connection import get_db
from mysql.connector import Error, IntegrityError

# Create a Blueprint for user routes
users = Blueprint("users", __name__)

# Must be present on create: the NOT NULL columns in ddl.sql that have no DEFAULT.
# user_uuid is generated by MySQL, not supplied by the client. account_status is
# omitted because ddl.sql defaults it to 'offline'.
required_fields = ["first_name", "last_name", "email", "date_account_creation", "location_id"]

# Columns a client may change. Whitelisting these is what makes the f-string
# UPDATE below safe from SQL injection, so never build it from raw request keys.
# date_account_creation is deliberately excluded: it is a creation fact, not editable.
updatable_fields = ["first_name", "last_name", "email", "phone", "dob",
                    "gender", "account_status", "custom_status_message", "location_id"]


@users.route("/users", methods=["GET"])
def get_all_users():
    cursor = get_db().cursor(dictionary=True)
    try:
        current_app.logger.info('GET /users')
        first_name = request.args.get("first_name")
        last_name = request.args.get("last_name")
        email = request.args.get("email")
        dob = request.args.get("dob")

        query = """
            SELECT user_id, first_name, last_name, account_status,
                   custom_status_message, date_account_creation, location_id
            FROM user
            WHERE date_account_deletion IS NULL
        """
        params = []

        if first_name:
            query += " AND first_name = %s"
            params.append(first_name)
        if last_name:
            query += " AND last_name = %s"
            params.append(last_name)
        if email:
            query += " AND email = %s"
            params.append(email)
        if dob:
            query += " AND dob = %s"
            params.append(dob)

        cursor.execute(query, params)
        user_list = cursor.fetchall()

        current_app.logger.info(f'Retrieved {len(user_list)} users')
        return jsonify(user_list), 200
    except Error as e:
        current_app.logger.error(f'Database error in get_all_users: {e}')
        return jsonify({"error": str(e)}), 500
    finally:
        cursor.close()



@users.route("/users", methods=["POST"])
def create_user():
    cursor = get_db().cursor(dictionary=True)
    try:
        current_app.logger.info('POST /user/users')

        data = request.get_json(silent=True)
        if data is None:
            return jsonify({"error": "Request body must be valid JSON"}), 400

        for field in required_fields:
            if field not in data:
                return jsonify({"error": f"Missing required field: {field}"}), 400

        columns = [*required_fields]
        params = [data[c] for c in columns]

        for optional in ["account_status", "phone", "dob", "gender", "custom_status_message"]:
            if optional in data:
                columns.append(optional)
                params.append(data[optional])

        placeholders = ", ".join(["%s"] * len(columns))
        query = f"""
            INSERT INTO user (user_uuid, {', '.join(columns)})
            VALUES (UUID(), {placeholders})
        """
        cursor.execute(query, params)
        new_user_id = cursor.lastrowid
        get_db().commit()

        current_app.logger.info(f'Created user {new_user_id}')
        return jsonify({"message": "User created successfully", "user_id": new_user_id}), 201
    except IntegrityError:
        # email is UNIQUE, and location_id is a foreign key
        current_app.logger.warning('create_user: integrity constraint violated')
        return jsonify({"error": "A user with that email already exists, or location_id is invalid"}), 409
    except Error as e:
        current_app.logger.error(f'Database error in create_user: {e}')
        return jsonify({"error": str(e)}), 500
    finally:
        cursor.close()




@users.route("/users/<int:user_id>", methods=["PUT"])
def update_user(user_id):
    cursor = get_db().cursor(dictionary=True)
    try:
        current_app.logger.info(f'PUT /user/users/{user_id}')

        data = request.get_json(silent=True)
        if data is None:
            return jsonify({"error": "Request body must be valid JSON"}), 400

        cursor.execute("SELECT user_id FROM user WHERE user_id = %s", (user_id,))
        if not cursor.fetchone():
            return jsonify({"error": "User not found"}), 404

        update_fields = [f"{f} = %s" for f in updatable_fields if f in data]
        params = [data[f] for f in updatable_fields if f in data]
        if not update_fields:
            return jsonify({"error": "No valid fields to update"}), 400

        params.append(user_id)
        query = f"UPDATE user SET {', '.join(update_fields)} WHERE user_id = %s"
        cursor.execute(query, params)
        get_db().commit()

        current_app.logger.info(f'Updated user {user_id}')
        return jsonify({"message": "User updated successfully"}), 200

    except IntegrityError:
        current_app.logger.warning(f'update_user {user_id}: integrity constraint violated')
        return jsonify({"error": "A user with that email already exists, or location_id is invalid"}), 409
    except Error as e:
        current_app.logger.error(f'Database error in update_user: {e}')
        return jsonify({"error": str(e)}), 500
    finally:
        cursor.close()

